@host=http://localhost:3000/api/v1

### Access public Resource
GET http://localhost:3000/api/v1/public/.well-known/ec.jwks.json

#### GET User route --->
GET {{host}}/user

### POST User register route ---> /register
POST {{host}}/user/register
Content-Type: application/json

{
  "email":"kismat1@nielit.gov.in",
  "password":"1234"
}

### POST User register route ---> /register
POST {{host}}/user/login
Content-Type: application/json

{
  "email":"kismat1@nielit.gov.in",
  "password":"1234",
  "test":"sdfgjsdf"
}

### PUT User route--->
PUT {{host}}/user

### PATCH User route--->
PATCH {{host}}/user

### Not Existing route
GET {{host}}/user/run
